### ISSUE TITLE
LOTS of microstutter

### ISSUE THREAD

**Issue by tooandrew** [Patchier/Tend-to-your-Frontier#1]
i have a lot of microstutter with this mod list that i dont have with stock. my framerate counter says 130 or whatever but it keeps dropping to like 90 which makes it feel like 30 or something. see linked video
https://youtu.be/ie8dg25WqEQ

**Comment by tooandrew** [comment]
specs are 2080 ti and 9900k 32gb 3200mhz ram

**Comment by Patchier** [comment]
Ok

**Comment by tooandrew** [comment]
cool, thanks bro
